params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: kvasir_shard_descriptor.KvasirShardDescriptor
  params:
    data_folder: kvasir_data
    rank_worldsize: 9,10
    enforce_image_hw: '400,400'
  