params:
  cuda_devices: []

optional_plugin_components: {}

shard_descriptor:
  template: gear_shard_descriptor.GearShardDescriptor
  params:
    data_folder: dataset
    rank_worldsize: 2,10
    enforce_image_hw: '300,400'
  